@startuml

title __PICKIMAGEBASE's Class Diagram__\n

  namespace com.architectica.socialcomponents {
    namespace main.pickImageBase {
      abstract class com.architectica.socialcomponents.main.pickImageBase.PickImageActivity {
          # imageUri : Uri
          {static} - SAVED_STATE_IMAGE_URI : String
          + hideLocalProgress()
          + loadImageToImageView()
          + onRequestPermissionsResult()
          + onSelectImageClick()
          {abstract} # getImageView()
          {abstract} # getProgressView()
          # handleCropImageResult()
          # onActivityResult()
          {abstract} # onImagePikedAction()
          # onRestoreInstanceState()
          # onSaveInstanceState()
          # startCropImageActivity()
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace main.pickImageBase {
      class com.architectica.socialcomponents.main.pickImageBase.PickImagePresenter {
          {static} # MAX_FILE_SIZE_IN_BYTES : int
          + PickImagePresenter()
          + isImageFileValid()
          # handleCropImageResult()
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace main.pickImageBase {
      interface com.architectica.socialcomponents.main.pickImageBase.PickImageView {
          {abstract} + hideLocalProgress()
          {abstract} + loadImageToImageView()
      }
    }
  }
  

  com.architectica.socialcomponents.main.pickImageBase.PickImageActivity .up.|> com.architectica.socialcomponents.main.pickImageBase.PickImageView
  com.architectica.socialcomponents.main.pickImageBase.PickImageActivity -up-|> com.architectica.socialcomponents.main.base.BaseActivity
  com.architectica.socialcomponents.main.pickImageBase.PickImagePresenter -up-|> com.architectica.socialcomponents.main.base.BasePresenter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
