@startuml

title __USERS's Class Diagram__\n

  namespace com.architectica.socialcomponents {
    namespace main.search {
      namespace users {
        class com.architectica.socialcomponents.main.search.users.SearchUsersBySkillsFragment {
            - emptyListMessageTextView : TextView
            - lastSearchText : String
            - progressBar : ProgressBar
            - recyclerView : RecyclerView
            - searchInProgress : boolean
            - selectedItemPosition : int
            + SearchUsersBySkillsFragment()
            + createPresenter()
            + hideLocalProgress()
            + onActivityResult()
            + onCreate()
            + onCreateView()
            + onSearchResultsReady()
            + search()
            + showEmptyListLayout()
            + showLocalProgress()
            + updateSelectedItem()
            - initRecyclerView()
            - openProfileActivity()
        }
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace main.search {
      namespace users {
        class com.architectica.socialcomponents.main.search.users.SearchUsersFragment {
            - emptyListMessageTextView : TextView
            - lastSearchText : String
            - progressBar : ProgressBar
            - recyclerView : RecyclerView
            - searchInProgress : boolean
            - selectedItemPosition : int
            + SearchUsersFragment()
            + createPresenter()
            + hideLocalProgress()
            + onActivityResult()
            + onCreate()
            + onCreateView()
            + onSearchResultsReady()
            + search()
            + showEmptyListLayout()
            + showLocalProgress()
            + updateSelectedItem()
            - initRecyclerView()
            - openProfileActivity()
        }
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace main.search {
      namespace users {
        class com.architectica.socialcomponents.main.search.users.SearchUsersPresenter {
            - activity : Activity
            - currentUserId : String
            + SearchUsersPresenter()
            + loadUsersWithEmptySearch()
            + onFollowButtonClick()
            + search()
            + searchBySkill()
            + unfollowUser()
            - followUser()
        }
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace main.search {
      namespace users {
        interface com.architectica.socialcomponents.main.search.users.SearchUsersView {
            {abstract} + hideLocalProgress()
            {abstract} + onSearchResultsReady()
            {abstract} + showEmptyListLayout()
            {abstract} + showLocalProgress()
            {abstract} + updateSelectedItem()
        }
      }
    }
  }
  

  com.architectica.socialcomponents.main.search.users.SearchUsersBySkillsFragment .up.|> com.architectica.socialcomponents.main.search.Searchable
  com.architectica.socialcomponents.main.search.users.SearchUsersBySkillsFragment .up.|> com.architectica.socialcomponents.main.search.users.SearchUsersView
  com.architectica.socialcomponents.main.search.users.SearchUsersBySkillsFragment -up-|> com.architectica.socialcomponents.main.base.BaseFragment
  com.architectica.socialcomponents.main.search.users.SearchUsersBySkillsFragment o-- com.architectica.socialcomponents.adapters.SearchUsersAdapter : usersAdapter
  com.architectica.socialcomponents.main.search.users.SearchUsersFragment .up.|> com.architectica.socialcomponents.main.search.Searchable
  com.architectica.socialcomponents.main.search.users.SearchUsersFragment .up.|> com.architectica.socialcomponents.main.search.users.SearchUsersView
  com.architectica.socialcomponents.main.search.users.SearchUsersFragment -up-|> com.architectica.socialcomponents.main.base.BaseFragment
  com.architectica.socialcomponents.main.search.users.SearchUsersFragment o-- com.architectica.socialcomponents.adapters.SearchUsersAdapter : usersAdapter
  com.architectica.socialcomponents.main.search.users.SearchUsersPresenter -up-|> com.architectica.socialcomponents.main.base.BasePresenter
  com.architectica.socialcomponents.main.search.users.SearchUsersPresenter o-- com.architectica.socialcomponents.managers.FollowManager : followManager
  com.architectica.socialcomponents.main.search.users.SearchUsersPresenter o-- com.architectica.socialcomponents.managers.ProfileManager : profileManager


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
