@startuml

title __VIEWPAGER's Class Diagram__\n

  namespace com.architectica.socialcomponents {
    namespace adapters {
      namespace viewPager {
        abstract class com.architectica.socialcomponents.adapters.viewPager.SmartFragmentStatePagerAdapter {
            - registeredFragments : Map<Integer, Fragment>
            + SmartFragmentStatePagerAdapter()
            + destroyItem()
            + getRegisteredFragment()
            + instantiateItem()
        }
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace adapters {
      namespace viewPager {
        class com.architectica.socialcomponents.adapters.viewPager.TabsPagerAdapter {
            - mActivity : FragmentActivity
            - mTabs : ArrayList<TabInfo>
            + TabsPagerAdapter()
            + addTab()
            + getCount()
            + getItem()
            + getPageTitle()
        }
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace adapters {
      namespace viewPager {
        class com.architectica.socialcomponents.adapters.viewPager.TabsPagerAdapter.TabInfo {
            ~ fragment : Fragment
            ~ title : String
            + TabInfo()
            + getFragment()
            + getTitle()
        }
      }
    }
  }
  

  com.architectica.socialcomponents.adapters.viewPager.SmartFragmentStatePagerAdapter -up-|> android.support.v4.app.FragmentStatePagerAdapter
  com.architectica.socialcomponents.adapters.viewPager.TabsPagerAdapter -up-|> com.architectica.socialcomponents.adapters.viewPager.SmartFragmentStatePagerAdapter
  com.architectica.socialcomponents.adapters.viewPager.TabsPagerAdapter +-down- com.architectica.socialcomponents.adapters.viewPager.TabsPagerAdapter.TabInfo


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
