@startuml

title __LOGIN's Class Diagram__\n

  namespace com.architectica.socialcomponents {
    namespace main.login {
      class com.architectica.socialcomponents.main.login.LoginActivity {
          {static} + LOGIN_REQUEST_CODE : int
          {static} - SIGN_IN_GOOGLE : int
          {static} - TAG : String
          - mAuth : FirebaseAuth
          - mAuthListener : AuthStateListener
          - mCallbackManager : CallbackManager
          - mGoogleApiClient : GoogleApiClient
          - profilePhotoUrlLarge : String
          + createPresenter()
          + firebaseAuthWithCredentials()
          + onActivityResult()
          + onConnectionFailed()
          + onStart()
          + onStop()
          + setProfilePhotoUrl()
          + signInWithFacebook()
          + signInWithGoogle()
          + startCreateProfileActivity()
          # onCreate()
          - initFacebookSignIn()
          - initFirebaseAuth()
          - initGoogleSignIn()
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace main.login {
      class com.architectica.socialcomponents.main.login.LoginPresenter {
          + checkIsProfileExist()
          + handleAuthError()
          + handleFacebookSignInResult()
          + handleGoogleSignInResult()
          + onFacebookSignInClick()
          + onGoogleSignInClick()
          ~ LoginPresenter()
          - buildFacebookPhotoUrl()
          - buildGooglePhotoUrl()
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace main.login {
      interface com.architectica.socialcomponents.main.login.LoginView {
          {abstract} + firebaseAuthWithCredentials()
          {abstract} + setProfilePhotoUrl()
          {abstract} + signInWithFacebook()
          {abstract} + signInWithGoogle()
          {abstract} + startCreateProfileActivity()
      }
    }
  }
  

  com.architectica.socialcomponents.main.login.LoginActivity .up.|> com.architectica.socialcomponents.main.login.LoginView
  com.architectica.socialcomponents.main.login.LoginActivity .up.|> com.google.android.gms.common.api.GoogleApiClient.OnConnectionFailedListener
  com.architectica.socialcomponents.main.login.LoginActivity -up-|> com.architectica.socialcomponents.main.base.BaseActivity
  com.architectica.socialcomponents.main.login.LoginPresenter -up-|> com.architectica.socialcomponents.main.base.BasePresenter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
