@startuml

title __LISTENERS's Class Diagram__\n

  namespace com.architectica.socialcomponents {
    namespace managers {
      namespace listeners {
        interface com.architectica.socialcomponents.managers.listeners.OnCountChangedListener {
            {abstract} + onCountChanged()
        }
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace managers {
      namespace listeners {
        interface com.architectica.socialcomponents.managers.listeners.OnDataChangedListener {
            {abstract} + onListChanged()
        }
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace managers {
      namespace listeners {
        interface com.architectica.socialcomponents.managers.listeners.OnObjectChangedListener {
            {abstract} + onError()
            {abstract} + onObjectChanged()
        }
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace managers {
      namespace listeners {
        abstract class com.architectica.socialcomponents.managers.listeners.OnObjectChangedListenerSimple {
            + onError()
        }
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace managers {
      namespace listeners {
        interface com.architectica.socialcomponents.managers.listeners.OnObjectExistListener {
            {abstract} + onDataChanged()
        }
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace managers {
      namespace listeners {
        interface com.architectica.socialcomponents.managers.listeners.OnPostChangedListener {
            {abstract} + onError()
            {abstract} + onObjectChanged()
        }
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace managers {
      namespace listeners {
        interface com.architectica.socialcomponents.managers.listeners.OnPostCreatedListener {
            {abstract} + onPostSaved()
        }
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace managers {
      namespace listeners {
        interface com.architectica.socialcomponents.managers.listeners.OnPostListChangedListener {
            {abstract} + onCanceled()
            {abstract} + onListChanged()
        }
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace managers {
      namespace listeners {
        interface com.architectica.socialcomponents.managers.listeners.OnProfileCreatedListener {
            {abstract} + onProfileCreated()
        }
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace managers {
      namespace listeners {
        interface com.architectica.socialcomponents.managers.listeners.OnRequestComplete {
            {abstract} + onComplete()
        }
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace managers {
      namespace listeners {
        interface com.architectica.socialcomponents.managers.listeners.OnTaskCompleteListener {
            {abstract} + onTaskComplete()
        }
      }
    }
  }
  

  com.architectica.socialcomponents.managers.listeners.OnObjectChangedListenerSimple .up.|> com.architectica.socialcomponents.managers.listeners.OnObjectChangedListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
