@startuml

title __CONTROLLERS's Class Diagram__\n

  namespace com.architectica.socialcomponents {
    namespace controllers {
      class com.architectica.socialcomponents.controllers.LikeController {
          {static} - ANIMATION_DURATION : int
          - context : Context
          - isLiked : boolean
          - isListView : boolean
          - likeCounterTextView : TextView
          - likesImageView : ImageView
          - postAuthorId : String
          - postId : String
          - updatingLikeCounter : boolean
          + LikeController()
          + changeAnimationType()
          + getLikeAnimationType()
          + handleLikeClickAction()
          + handleLikeClickAction()
          + initLike()
          + isLiked()
          + isUpdatingLikeCounter()
          + likeClickAction()
          + likeClickActionLocal()
          + setLikeAnimationType()
          + setLiked()
          + setUpdatingLikeCounter()
          - addLike()
          - adjustAlpha()
          - bounceAnimateImageView()
          - colorAnimateImageView()
          - doHandleLikeClickAction()
          - removeLike()
          - showWarningMessage()
          - startAnimateLikeButton()
          - updateLocalPostLikeCounter()
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace controllers {
      enum AnimationType {
        BOUNCE_ANIM
        COLOR_ANIM
      }
    }
  }
  

  com.architectica.socialcomponents.controllers.LikeController o-- com.architectica.socialcomponents.controllers.LikeController.AnimationType : likeAnimationType
  com.architectica.socialcomponents.controllers.LikeController +-down- com.architectica.socialcomponents.controllers.LikeController.AnimationType


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
