@startuml

title __SOCIALCOMPONENTS's Class Diagram__\n

  namespace com.architectica.socialcomponents {
    class com.architectica.socialcomponents.Application {
        {static} + TAG : String
        + onCreate()
    }
  }
  

  namespace com.architectica.socialcomponents {
    class com.architectica.socialcomponents.ApplicationHelper {
        {static} - TAG : String
        {static} - databaseHelper : DatabaseHelper
        {static} + getDatabaseHelper()
        {static} + initDatabaseHelper()
    }
  }
  

  namespace com.architectica.socialcomponents {
    class com.architectica.socialcomponents.Constants {
    }
  }
  

  namespace com.architectica.socialcomponents {
    class com.architectica.socialcomponents.Constants.Database {
        {static} + MAX_UPLOAD_RETRY_MILLIS : int
    }
  }
  

  namespace com.architectica.socialcomponents {
    class com.architectica.socialcomponents.Constants.General {
        {static} + DOUBLE_CLICK_TO_EXIT_INTERVAL : long
    }
  }
  

  namespace com.architectica.socialcomponents {
    class com.architectica.socialcomponents.Constants.Post {
        {static} + MAX_POST_TITLE_LENGTH : int
        {static} + MAX_TEXT_LENGTH_IN_LIST : int
        {static} + POST_AMOUNT_ON_PAGE : int
    }
  }
  

  namespace com.architectica.socialcomponents {
    class com.architectica.socialcomponents.Constants.Profile {
        {static} + MAX_AVATAR_SIZE : int
        {static} + MAX_NAME_LENGTH : int
        {static} + MIN_AVATAR_SIZE : int
    }
  }
  

  namespace com.architectica.socialcomponents {
    class com.architectica.socialcomponents.Constants.PushNotification {
        {static} + LARGE_ICONE_SIZE : int
    }
  }
  

  com.architectica.socialcomponents.Application -up-|> android.app.Application
  com.architectica.socialcomponents.Constants +-down- com.architectica.socialcomponents.Constants.Database
  com.architectica.socialcomponents.Constants +-down- com.architectica.socialcomponents.Constants.General
  com.architectica.socialcomponents.Constants +-down- com.architectica.socialcomponents.Constants.Post
  com.architectica.socialcomponents.Constants +-down- com.architectica.socialcomponents.Constants.Profile
  com.architectica.socialcomponents.Constants +-down- com.architectica.socialcomponents.Constants.PushNotification


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
