@startuml

title __SEARCH's Class Diagram__\n

  namespace com.architectica.socialcomponents {
    namespace main.search {
      class com.architectica.socialcomponents.main.search.SearchActivity {
          {static} - TAG : String
          - searchView : SearchView
          - tabLayout : TabLayout
          - viewPager : ViewPager
          + createPresenter()
          + onCreateOptionsMenu()
          # onCreate()
          - initContentView()
          - initSearch()
          - initTabs()
          - search()
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace main.search {
      class com.architectica.socialcomponents.main.search.SearchPresenter {
          - activity : Activity
          - currentUserId : String
          + search()
          ~ SearchPresenter()
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace main.search {
      interface com.architectica.socialcomponents.main.search.SearchView {
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace main.search {
      interface com.architectica.socialcomponents.main.search.Searchable {
          {abstract} + search()
      }
    }
  }
  

  com.architectica.socialcomponents.main.search.SearchActivity .up.|> com.architectica.socialcomponents.main.search.SearchView
  com.architectica.socialcomponents.main.search.SearchActivity -up-|> com.architectica.socialcomponents.main.base.BaseActivity
  com.architectica.socialcomponents.main.search.SearchActivity o-- com.architectica.socialcomponents.adapters.viewPager.TabsPagerAdapter : tabsAdapter
  com.architectica.socialcomponents.main.search.SearchPresenter -up-|> com.architectica.socialcomponents.main.base.BasePresenter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
