@startuml

title __SERVICES's Class Diagram__\n

  namespace com.architectica.socialcomponents {
    namespace services {
      class com.architectica.socialcomponents.services.MyFirebaseInstanceIDService {
          {static} - TAG : String
          + onTokenRefresh()
          - sendRegistrationToServer()
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace services {
      class com.architectica.socialcomponents.services.MyFirebaseMessagingService {
          {static} - ACTION_TYPE_KEY : String
          {static} - ACTION_TYPE_NEW_ADMIN_NOTIFICATION : String
          {static} - ACTION_TYPE_NEW_COMMENT : String
          {static} - ACTION_TYPE_NEW_LIKE : String
          {static} - ACTION_TYPE_NEW_POST : String
          {static} - AUTHOR_ID_KEY : String
          {static} - BODY_KEY : String
          {static} - ICON_KEY : String
          {static} - POST_ID_KEY : String
          {static} - TAG : String
          {static} - TITLE_KEY : String
          {static} - notificationId : int
          + getBitmapFromUrl()
          + onMessageReceived()
          - adminNotification()
          - handleNewPostCreatedAction()
          - handleRemoteMessage()
          - parseCommentOrLike()
          - sendNotification()
          - sendNotification()
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace services {
      enum Channel {
        NEW_COMMENT
        NEW_LIKE
        id
        name
      }
    }
  }
  

  com.architectica.socialcomponents.services.MyFirebaseInstanceIDService -up-|> com.google.firebase.iid.FirebaseInstanceIdService
  com.architectica.socialcomponents.services.MyFirebaseMessagingService -up-|> com.google.firebase.messaging.FirebaseMessagingService
  com.architectica.socialcomponents.services.MyFirebaseMessagingService +-down- com.architectica.socialcomponents.services.MyFirebaseMessagingService.Channel


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
