@startuml

title __CHAT's Class Diagram__\n

  namespace com.architectica.socialcomponents {
    namespace main.Chat {
      class com.architectica.socialcomponents.main.Chat.ChatActivity {
          ~ userName : String
          {static} - GALLERY_PICK : int
          {static} - TOTAL_ITEMS_TO_LOAD : int
          - itemPos : int
          - mAuth : FirebaseAuth
          - mChatAddBtn : ImageButton
          - mChatMessageView : EditText
          - mChatSendBtn : ImageButton
          - mChatToolbar : Toolbar
          - mChatUser : String
          - mCurrentPage : int
          - mCurrentUserId : String
          - mImageStorage : StorageReference
          - mLastKey : String
          - mLinearLayout : LinearLayoutManager
          - mMessagesList : RecyclerView
          - mPrevKey : String
          - mRefreshLayout : SwipeRefreshLayout
          - mRootRef : DatabaseReference
          - mTitleView : TextView
          - messagesList : List<Messages>
          + onOptionsItemSelected()
          # onActivityResult()
          # onCreate()
          - loadMessages()
          - loadMoreMessages()
          - sendMessage()
      }
    }
  }
  

  com.architectica.socialcomponents.main.Chat.ChatActivity -up-|> android.support.v7.app.AppCompatActivity
  com.architectica.socialcomponents.main.Chat.ChatActivity o-- com.architectica.socialcomponents.adapters.MessageAdapter : mAdapter
  com.architectica.socialcomponents.main.Chat.ChatActivity o-- com.architectica.socialcomponents.views.CircularImageView : mProfileImage


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
