@startuml

title __DIALOGS's Class Diagram__\n

  namespace com.architectica.socialcomponents {
    namespace dialogs {
      class com.architectica.socialcomponents.dialogs.EditCommentDialog {
          {static} + COMMENT_ID_KEY : String
          {static} + COMMENT_TEXT_KEY : String
          {static} + TAG : String
          - commentId : String
          - commentText : String
          + onCreate()
          + onCreateDialog()
          - configureDialogButtonState()
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace dialogs {
      interface com.architectica.socialcomponents.dialogs.EditCommentDialog.CommentDialogCallback {
          {abstract} + onCommentChanged()
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace dialogs {
      class com.architectica.socialcomponents.dialogs.UnfollowConfirmationDialog {
          {static} + PROFILE : String
          {static} + TAG : String
          + onCreate()
          + onCreateDialog()
      }
    }
  }
  

  namespace com.architectica.socialcomponents {
    namespace dialogs {
      interface com.architectica.socialcomponents.dialogs.UnfollowConfirmationDialog.Callback {
          {abstract} + onUnfollowButtonClicked()
      }
    }
  }
  

  com.architectica.socialcomponents.dialogs.EditCommentDialog -up-|> android.app.DialogFragment
  com.architectica.socialcomponents.dialogs.EditCommentDialog o-- com.architectica.socialcomponents.dialogs.EditCommentDialog.CommentDialogCallback : callback
  com.architectica.socialcomponents.dialogs.EditCommentDialog +-down- com.architectica.socialcomponents.dialogs.EditCommentDialog.CommentDialogCallback
  com.architectica.socialcomponents.dialogs.UnfollowConfirmationDialog -up-|> android.app.DialogFragment
  com.architectica.socialcomponents.dialogs.UnfollowConfirmationDialog o-- com.architectica.socialcomponents.dialogs.UnfollowConfirmationDialog.Callback : callback
  com.architectica.socialcomponents.dialogs.UnfollowConfirmationDialog o-- com.architectica.socialcomponents.model.Profile : profile
  com.architectica.socialcomponents.dialogs.UnfollowConfirmationDialog +-down- com.architectica.socialcomponents.dialogs.UnfollowConfirmationDialog.Callback


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
